basePath: /
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://swagger.io/support/
  description: List API of Shop Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/license/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Shop API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
